const Employee = require('../models/Employee');
const Position = require('../models/Position');
const ScheduledPositionSwap = require('../models/ScheduledPositionSwap');
const RestDayHistory = require('../models/RestDayHistory');
const Shift = require('../models/Shift');
const ShiftCategory = require('../models/ShiftCategory');
const { toDateKey } = require('./attendanceProcessor');
const { resolveRestDayForPosition } = require('./restDayRules');

// Attendance (recomputeDay/resolveExpectedShift) always reads an employee's
// CURRENT position/defaultShiftCategory live, at the moment each scan comes
// in — there's no snapshot. That's a problem specifically on the swap's own
// effective date: the Employee fields below flip the moment this function
// runs, but that could land anywhere from midnight to ~15 minutes later (see
// index.js's recurring check) or instantly if an admin happens to open the
// swap list page — so a scan arriving right at shift-start on that exact day
// could get evaluated against whichever side of the flip it happens to race.
// Pinning a 'scheduled' Shift override for that one date removes the race
// entirely: resolveExpectedShift checks for a same-date Shift override
// FIRST, before ever falling back to the live position/category, so the old
// schedule governs the whole transition day no matter when the flip lands.
// This is the general/fallback treatment — pins each mover's own unchanged
// old shift for one day. Used whenever the two positions' old shifts don't
// cleanly tile a 24-hour day (see applyPositionSwap); the real ກະເຊົ້າ/ກະແລງ
// pattern gets the more specific extend/blank treatment right below instead.
// Skipped if the employee already has any Shift for that date that an admin
// set by hand (their explicit choice for that specific day wins over this
// automatic one) — but not skipped for a pin this same mechanism created
// earlier (see isAutoGeneratedSwapPin), so swapping the same two positions
// back on the same day re-derives today correctly instead of leaving a
// stale pin from the first swap behind. Also skipped for someone who had no
// shift time to snapshot in the first place.
const AUTO_SWAP_PIN_NOTE_PREFIX = 'ສ້າງອັດຕະໂນມັດ';
function isAutoGeneratedSwapPin(shift) {
  return typeof shift.note === 'string' && shift.note.startsWith(AUTO_SWAP_PIN_NOTE_PREFIX);
}
async function clearAutoPinIfAny(employeeId, effectiveDate) {
  const existing = await Shift.findOne({ employee: employeeId, date: effectiveDate });
  if (!existing) return true;
  if (!isAutoGeneratedSwapPin(existing)) return false;
  await Shift.deleteOne({ _id: existing._id });
  return true;
}

async function pinOldScheduleForSwapDay(employee, oldPositionId, effectiveDate) {
  const hasCategory = !!employee.defaultShiftCategory;
  if (!hasCategory && !(employee.defaultShiftStart && employee.defaultShiftEnd)) return;
  if (!(await clearAutoPinIfAny(employee._id, effectiveDate))) return;
  let startTime = employee.defaultShiftStart;
  let endTime = employee.defaultShiftEnd;
  if (hasCategory) {
    const category = await ShiftCategory.findById(employee.defaultShiftCategory);
    if (!category) return;
    startTime = category.startTime;
    endTime = category.endTime;
  }
  await Shift.create({
    employee: employee._id,
    position: oldPositionId,
    category: hasCategory ? employee.defaultShiftCategory : undefined,
    date: effectiveDate,
    status: 'scheduled',
    startTime,
    endTime,
    note: 'ສ້າງອັດຕະໂນມັດ — ຮັກສາຕາຕະລາງເກົ່າໄວ້ໃນມື້ສະຫຼັບຕຳແໜ່ງ',
  });
}

// Resolves a concrete {startTime, endTime} for whichever employee
// canonicalTimeOf() read the group's time from (fetching the category if
// that's how it was set) — needed to compare the two positions' old shift
// times and decide which swap-day treatment applies. Null when there's
// nothing to resolve (empty position, or a category that's been deleted).
async function resolveCanonicalTime(canonical) {
  if (canonical.categoryId) {
    const category = await ShiftCategory.findById(canonical.categoryId);
    return category ? { startTime: category.startTime, endTime: category.endTime } : null;
  }
  if (canonical.start && canonical.end) return { startTime: canonical.start, endTime: canonical.end };
  return null;
}

// One minute before `time` (HH:mm). isOvernightShift only compares hour and
// minute, with no cap on how long an "overnight" shift can run — so an
// override whose endTime is a single minute earlier than its startTime reads
// as running the full next calendar day through to just before that same
// clock time again, which is exactly the "one continuous ~24h shift" the
// early-leaving group below needs, without touching that shared comparison.
function oneMinuteBefore(time) {
  const [h, m] = time.split(':').map(Number);
  const total = (h * 60 + m - 1 + 24 * 60) % (24 * 60);
  return `${String(Math.floor(total / 60)).padStart(2, '0')}:${String(total % 60).padStart(2, '0')}`;
}

// The ກະເຊົ້າ/ກະແລງ pattern: the two positions' old shifts exactly tile a
// 24-hour day (e.g. 06:00-18:00 and 18:00-06:00). Calling back someone who
// already went home for one more rotation is worse than having whoever's
// already on site work straight through — so on the swap day, the group
// leaving the EARLIER-starting shift works one continuous ~24h shift
// covering both halves of the day (pinExtendedScheduleForSwapDay), and the
// group leaving the LATER-starting shift has nothing scheduled that day at
// all (pinBlankScheduleForSwapDay) — their last real occurrence already
// ended earlier that same morning, and their first new-schedule shift starts
// clean the day after. Both skip an employee who already has a Shift that
// date, same as the general case above.
async function pinExtendedScheduleForSwapDay(employee, oldPositionId, startTime, lateEnd, categoryId, effectiveDate) {
  if (!(await clearAutoPinIfAny(employee._id, effectiveDate))) return;
  // Normally ends exactly where the late shift itself ends (e.g. 06:00) —
  // that's what "cover through the handover point" actually means. Only
  // falls back to the one-minute-before trick when the two shifts tile with
  // zero gap, where lateEnd === startTime would otherwise look like a
  // zero-length shift to isOvernightShift instead of a ~24h one.
  const endTime = lateEnd === startTime ? oneMinuteBefore(startTime) : lateEnd;
  await Shift.create({
    employee: employee._id,
    position: oldPositionId,
    // Without this, resolveExpectedShift's grace/severeLate/autoAbsent policy
    // for this one day silently falls back to the hardcoded module defaults
    // instead of whatever the old category actually has configured — carrying
    // it over keeps the day's late/absent labels consistent with every other
    // day this group worked that shift.
    category: categoryId ?? undefined,
    date: effectiveDate,
    status: 'scheduled',
    startTime,
    endTime,
    note: 'ສ້າງອັດຕະໂນມັດ — ເຮັດວຽກຕໍ່ເນື່ອງຍາວໃນມື້ສະຫຼັບຕຳແໜ່ງ',
  });
}

async function pinBlankScheduleForSwapDay(employee, effectiveDate) {
  if (!(await clearAutoPinIfAny(employee._id, effectiveDate))) return;
  await Shift.create({
    employee: employee._id,
    date: effectiveDate,
    status: 'swapped',
    note: 'ສ້າງອັດຕະໂນມັດ — ບໍ່ມີກະໃນມື້ສະຫຼັບຕຳແໜ່ງ',
  });
}

// A mover's own rest day carries over unchanged unless their NEW position
// forbids it, in which case it's redirected to that position's configured
// fallback right here — the same rule employees.js/shifts.js apply when
// someone picks a rest day by hand, just applied automatically since nobody
// is sitting at a form during a swap. Returns the resolved day (only when it
// actually changed) so the caller can fold it into the same Employee.updateOne
// as everything else the swap already touches; returns null when nothing
// needs to change, including the case where the day IS forbidden but the
// position has no fallback configured — that's left as-is, same gap as
// before this existed, since there's no admin to ask mid-swap.
async function resolveMoverRestDay(employee, newPosition) {
  if (employee.defaultRestDay == null) return null;
  let resolved;
  try {
    resolved = resolveRestDayForPosition(newPosition, employee.defaultRestDay);
  } catch {
    return null;
  }
  if (resolved === employee.defaultRestDay) return null;
  await RestDayHistory.create({
    employee: employee._id,
    previousRestDay: employee.defaultRestDay,
    newRestDay: resolved,
    changedByEmail: 'ລະບົບ (ສະຫຼັບຕຳແໜ່ງອັດຕະໂນມັດ)',
  });
  return resolved;
}

// Whoever currently holds a position all shares one working time (see the
// KTV server positions this was built for) — so swapping isn't a 1-to-1
// person pairing, it's "everyone in A moves to B and takes on B's time, and
// vice versa." The canonical time for a position is read off its first
// current member (sorted by employee code); an empty position has no time to
// hand out, so movers into it end up with no default shift set.
function canonicalTimeOf(list) {
  const ref = list[0];
  return {
    categoryId: ref?.defaultShiftCategory ?? null,
    start: ref && !ref.defaultShiftCategory ? ref.defaultShiftStart ?? null : null,
    end: ref && !ref.defaultShiftCategory ? ref.defaultShiftEnd ?? null : null,
  };
}

// Resolves each position's CURRENT membership at the moment this runs (not
// whatever it was when the swap was scheduled) and swaps them. This is what
// makes "schedule for next month" safe — anyone hired, moved, or resigned
// between now and the effective date is still handled correctly because
// membership is looked up fresh every time this actually executes.
async function applyPositionSwap(positionAId, positionBId, effectiveDate) {
  const [positionA, positionB, empListA, empListB] = await Promise.all([
    Position.findById(positionAId),
    Position.findById(positionBId),
    Employee.find({ position: positionAId, status: 'active' }).sort('employeeCode'),
    Employee.find({ position: positionBId, status: 'active' }).sort('employeeCode'),
  ]);

  const canonicalA = canonicalTimeOf(empListA);
  const canonicalB = canonicalTimeOf(empListB);

  if (effectiveDate) {
    const [oldTimeA, oldTimeB] = await Promise.all([resolveCanonicalTime(canonicalA), resolveCanonicalTime(canonicalB)]);
    // Real shift pairs usually don't tile exactly — a handover/cleaning gap
    // between one ending and the other starting (e.g. evening ends 06:00,
    // morning starts 07:00) is normal, not a sign these are unrelated shifts.
    // So this checks "sequential with no overlap" (each one's end at or
    // before the other's start) rather than requiring the boundaries to land
    // on the exact same minute.
    const toMinutes = (hhmm) => {
      const [h, m] = hhmm.split(':').map(Number);
      return h * 60 + m;
    };
    const tilesFullDay =
      !!oldTimeA &&
      !!oldTimeB &&
      toMinutes(oldTimeA.endTime) <= toMinutes(oldTimeB.startTime) &&
      toMinutes(oldTimeB.endTime) <= toMinutes(oldTimeA.startTime);

    if (tilesFullDay) {
      const aIsEarly = oldTimeA.startTime < oldTimeB.startTime;
      const earlyList = aIsEarly ? empListA : empListB;
      const earlyOldPositionId = aIsEarly ? positionAId : positionBId;
      const earlyStart = aIsEarly ? oldTimeA.startTime : oldTimeB.startTime;
      const earlyCategoryId = aIsEarly ? canonicalA.categoryId : canonicalB.categoryId;
      // The late shift's own end (e.g. 06:00), not "24h after the early
      // shift's start" — with a handover gap the two aren't the same instant,
      // and the whole point is covering through to where the late shift
      // itself would have ended.
      const lateEnd = aIsEarly ? oldTimeB.endTime : oldTimeA.endTime;
      const lateList = aIsEarly ? empListB : empListA;
      await Promise.all([
        ...earlyList.map((e) => pinExtendedScheduleForSwapDay(e, earlyOldPositionId, earlyStart, lateEnd, earlyCategoryId, effectiveDate)),
        ...lateList.map((e) => pinBlankScheduleForSwapDay(e, effectiveDate)),
      ]);
    } else {
      await Promise.all([
        ...empListA.map((e) => pinOldScheduleForSwapDay(e, positionAId, effectiveDate)),
        ...empListB.map((e) => pinOldScheduleForSwapDay(e, positionBId, effectiveDate)),
      ]);
    }
  }

  const [restDayUpdatesA, restDayUpdatesB] = await Promise.all([
    Promise.all(empListA.map((e) => resolveMoverRestDay(e, positionB))),
    Promise.all(empListB.map((e) => resolveMoverRestDay(e, positionA))),
  ]);

  // The designated head travels with the group, same as their shift time —
  // whoever led position A now leads wherever that group ended up (B), and
  // vice versa. So each mover keeps pointing at THEIR OWN old position's head
  // (positionA?.head for A-movers, positionB?.head for B-movers) rather than
  // picking up the other side's, and the positions' own `head` fields swap to
  // match so a later admin look-up of "who heads this position" agrees with it.
  await Promise.all([
    ...empListA.map((e, i) =>
      Employee.updateOne(
        { _id: e._id },
        {
          position: positionBId,
          positionHead: positionA?.head || null,
          defaultShiftCategory: canonicalB.categoryId,
          defaultShiftStart: canonicalB.start,
          defaultShiftEnd: canonicalB.end,
          ...(restDayUpdatesA[i] != null ? { defaultRestDay: restDayUpdatesA[i] } : {}),
        }
      )
    ),
    ...empListB.map((e, i) =>
      Employee.updateOne(
        { _id: e._id },
        {
          position: positionAId,
          positionHead: positionB?.head || null,
          defaultShiftCategory: canonicalA.categoryId,
          defaultShiftStart: canonicalA.start,
          defaultShiftEnd: canonicalA.end,
          ...(restDayUpdatesB[i] != null ? { defaultRestDay: restDayUpdatesB[i] } : {}),
        }
      )
    ),
    Position.updateOne({ _id: positionAId }, { head: positionB?.head || null }),
    Position.updateOne({ _id: positionBId }, { head: positionA?.head || null }),
  ]);

  return { movedFromA: empListA.length, movedFromB: empListB.length };
}

// Applies every pending scheduled swap whose effective date has arrived.
// Called on server startup (catches anything due while the server was down)
// and on a recurring timer — this app has no other background job runner, so
// a plain interval is the simplest thing that reliably fires a swap on a
// future date without needing the browser open.
async function runDueScheduledSwaps() {
  const todayKey = toDateKey(new Date());
  const due = await ScheduledPositionSwap.find({ status: 'pending', effectiveDate: { $lte: todayKey } });
  for (const swap of due) {
    // eslint-disable-next-line no-await-in-loop
    const { movedFromA, movedFromB } = await applyPositionSwap(swap.positionA, swap.positionB, swap.effectiveDate);
    swap.status = 'applied';
    swap.appliedAt = new Date();
    swap.movedFromA = movedFromA;
    swap.movedFromB = movedFromB;
    // eslint-disable-next-line no-await-in-loop
    await swap.save();
  }
  return due.length;
}

module.exports = { applyPositionSwap, runDueScheduledSwaps };
